<?php
// Review pool for compression socks (kompresijske čarape).
// Real Croatian reviews from Noriks_Reviews_DE_HR_HU.
$auto_reviews_en = array(
    array("name" => "Ivan K.", "text" => "Oduševljen sam koliko su čarape ugodne i kako se super nose."),
    array("name" => "Marko P.", "text" => "Ovo je savršena čarapa! Vrlo sam zadovoljan i preporučujem je dalje. 5 zvjezdica!"),
    array("name" => "Tomislav R.", "text" => "Odlično pristaju. Prava su milina."),
    array("name" => "Josip D.", "text" => "Ovo su najbolje kompresijske čarape koje sam dosad imao."),
    array("name" => "Luka M.", "text" => "Sve top, rado ponovno."),
    array("name" => "Petar G.", "text" => "super"),
    array("name" => "Ante B.", "text" => "Dobra, napredna stvar. Vrijeme potrebno za obuvanje čarapa znatno je kraće."),
    array("name" => "Nikola R.", "text" => "Vrlo dobra kvaliteta i izrada, nažalost sam ih morao vratiti jer su mi bile prekratke. Povrat i naknada kupovne cijene nisu bili nikakav problem — nakon slanja natrag sve je išlo vrlo brzo."),
    array("name" => "Matija S.", "text" => "Zasad još ne osjećam poboljšanje, ali ne odustajem. Obuvanje čarapa je, zahvaljujući patentnom zatvaraču, bez ikakvog napora. Lp"),
    array("name" => "Domagoj K.", "text" => "Patentni zatvarač mi je praktičan. No, budući da imam jače listove, imam poprilično problema sa zatvaranjem zatvarača. Možda bih trebao probati veličinu L, ali onda bi mi stopalo moglo biti preveliko? Kod veličine obuće 38."),
    array("name" => "Zvonimir P.", "text" => "Sve super, odlično pristaju. Ugodne za nošenje."),
    array("name" => "Branimir N.", "text" => "Načelno mi se sviđaju, samo mi se kod crnih čarapa pri zatvaranju zatvarača on stalno zaglavi na jednom jezičku i dalje ne ide. Svijetle čarape nosim svaki dan i dobro ispunjavaju svoju svrhu, ali ne baš kao one na recept."),
    array("name" => "Renato T.", "text" => "Za mene je pravo olakšanje obuti ih. Ne treba mi ni pet minuta za to."),
    array("name" => "Andrej M.", "text" => "Zamišljao sam to drugačije i udobnije."),
    array("name" => "Dino K.", "text" => "Lako se obuvaju. Dostavu sam primio nakon određenog vremena čekanja. Točnost pristajanja vrlo je dobra, za razliku od ranijih mjerenja u specijaliziranim trgovinama. Sustav patentnog zatvarača je stabilan. Zatvarače sam premjestio prema unutra, pa je potreban napor lakše savladiv. Nažalost, unutarnja zaštita zatvarača vrlo se brzo zaglavi. No, jedan vikend uvježbavanja trebao bi biti dovoljan. Nošenje je vrlo ugodno, bez znojnih stopala, bez stezanja na rubovima. Izuvanje je jednostavno genijalno lako — ne traži ni prekomjeran napor ni tuđu pomoć."),
    array("name" => "Krešimir V.", "text" => "Čarapa se dobro obuva. Jedino što mogu zamjeriti jest patentni zatvarač koji se tijekom nošenja sam otvara. Bilo bi lijepo kad bi zatvarač imao mali osigurač koji sprječava samostalno otvaranje. Inače, ugodna za nošenje."),
    array("name" => "Goran L.", "text" => "Patentni zatvarač ipak se ne zatvara tako lako kao u vašim reklamama. No, uz malo vježbe ide sasvim dobro. Omjer cijene i kvalitete točan. Opseg lista malo pretijesan za veličinu obuće 36."),
    array("name" => "Stjepan C.", "text" => "Potpuno zadovoljan."),
    array("name" => "Vedran M.", "text" => "Prvo obuvanje bilo je malo teško, ali inače stvarno super."),
    array("name" => "Robert S.", "text" => "Čarape su mi znatno pretijesne. Manja veličina bila je namijenjena mom ocu; i veće su toliko tijesne da ne može sam zatvoriti patentni zatvarač. Čarapu treba stisnuti gore, iznad zatvarača — samo tako ide."),
    array("name" => "Davor H.", "text" => "Totalno sam oduševljen 🤩"),
    array("name" => "Mislav J.", "text" => "Zasad 👍"),
    array("name" => "Filip B.", "text" => "Stvarno sam oduševljen koliko se lako čarape obuvaju i koliko su ugodne za nošenje."),
    array("name" => "Dario N.", "text" => "Poštovani, godinama se mučim s kompresijskim čarapama klase 3 s pomagalima za navlačenje. Obuvanje bez pomoći, zahvaljujući mojoj pokretljivosti i snazi, još uvijek ide sasvim dobro. Onda sam naišao na vas. Unatoč strahu da kompresija možda neće biti dovoljna, izmjerio sam se i naručio. Potpuno sam očaran udobnošću nošenja — proći kroz dan bez bolova naprosto je neopisivo, a još udobnije obuvanje i izuvanje pravi je bonus, hvala patentnom zatvaraču. Jednako pozitivno ocjenjujem glatak tijek narudžbe i korisničku podršku. I ubuduće ću naručivati kod vas."),
    array("name" => "Zlatko M.", "text" => "Vrlo dobro rješenje. Nošenje se gotovo i ne primjećuje. Sviđa mi se."),
    array("name" => "Boris T.", "text" => "Udobno pri izuvanju."),
);
